### ISSUE TITLE
InCallScope + Factory + Context preservation don't give expected results

### ISSUE THREAD

**Issue by cervengoc** [ninject/Ninject.Extensions.ContextPreservation#4]
Please see the following SO post, and forgive me for not replicating the post here (I'll do it in the future for keeping things clear).

http://stackoverflow.com/questions/35360309/ninject-factory-incallscope-contextpreservation

**Comment by cervengoc** [comment]
Is anybody reading issues here, or is there any other place where this project is maintained?
@remogloor could you please drop me a few sentence on this?

**Comment by scott-xu** [comment]
There are 2 calls. One is `kernel.Get<Parent>()`, another is `instance.init()`

**Comment by cervengoc** [comment]
@scott-xu Thank you for the valuable information. After one year you point out the key of my sample code and close the issue immediately :)

I intentionally have two separate calls using **the same factoy instance**. Without context preservation, of course I'm starting two separate *call context*. 

But in my understanding the whole concept of *preserving context* would be that the first *call scope* context is preserved in the factory instance and every further requests to the factory will create a new object in the preserved context, so in the root call scope. I hope it makes sense. Please point me to the right direction if this is not true.
