### ISSUE TITLE
Support Ninject 3.3

### ISSUE THREAD

**Issue by msnelling** [ninject/Ninject.Extensions.ContextPreservation#5]
Hi,
We have an internal library using Ninject that targets .NETStandard 2.0 and only Ninject 3.3 supports this. Can you please release a version of this library that includes 3.3 as a dependency? Currently the .nuspec file specifies Ninject (>= 3.2.0 && < 3.3.0).

**Comment by scott-xu** [comment]
3.3.0 released.
